// @ts-ignore — generated by wasm-pack after `pnpm build:wasm`
import wasmInit from '../wasm/numjs_core.js';

let initPromise: Promise<void> | null = null;

/**
 * Load the WASM module. Must be called once before using any numjs functions.
 *
 * @example
 * import { init, np } from '@numjs/core';
 * await init();
 * const a = np.zeros([3, 3]);
 */
export function init(): Promise<void> {
  if (!initPromise) {
    initPromise = (wasmInit as () => Promise<unknown>)().then(() => undefined);
  }
  return initPromise;
}
