// @ts-ignore — generated by wasm-pack after `pnpm build:wasm`
import {
  NdArray as WasmNdArray,
  zeros as wasmZeros,
  ones as wasmOnes,
  arange as wasmArange,
  linspace as wasmLinspace,
} from '../wasm/numjs_core.js';

import type { NumArray, Shape } from './types';

const u32 = (shape: Shape): Uint32Array => new Uint32Array(shape);

// ── Creation ──────────────────────────────────────────────────────────────────

/**
 * Create an NdArray from a nested or flat JS array.
 *
 * @param data - Flat number array
 * @param shape - Shape of the array, e.g. [2, 3]
 *
 * @example
 * const a = np.array([1,2,3,4,5,6], [2,3]);
 */
function array(data: number[], shape?: Shape): NumArray {
  const flat = new Float64Array(data);
  const s = shape ?? [data.length];
  return new WasmNdArray(flat, u32(s)) as NumArray;
}

/**
 * Create an array filled with zeros.
 *
 * @example
 * const a = np.zeros([3, 3]); // 3x3 matrix of zeros
 */
function zeros(shape: Shape): NumArray {
  return wasmZeros(u32(shape)) as NumArray;
}

/**
 * Create an array filled with ones.
 *
 * @example
 * const a = np.ones([2, 4]); // 2x4 matrix of ones
 */
function ones(shape: Shape): NumArray {
  return wasmOnes(u32(shape)) as NumArray;
}

/**
 * Create a 1-D array with evenly spaced values in [start, stop).
 *
 * Matches NumPy's flexible signature — arguments after `stop` are optional
 * and resolved in the Rust/WASM core.
 *
 * @example
 * np.arange(5);          // [0, 1, 2, 3, 4]
 * np.arange(1, 5);       // [1, 2, 3, 4]
 * np.arange(0, 10, 2);   // [0, 2, 4, 6, 8]
 */
function arange(stop: number): NumArray;
function arange(start: number, stop: number): NumArray;
function arange(start: number, stop: number, step: number): NumArray;
function arange(a: number, b?: number, c?: number): NumArray {
  return wasmArange(a, b, c) as NumArray;
}

/**
 * Create a 1-D array with `num` evenly spaced values in the closed interval [start, stop].
 *
 * @param num - Number of samples. Defaults to `50` (NumPy-compatible).
 *
 * @example
 * np.linspace(0, 1);     // 50 evenly spaced points in [0, 1]
 * np.linspace(0, 1, 5);  // [0, 0.25, 0.5, 0.75, 1]
 */
function linspace(start: number, stop: number, num?: number): NumArray {
  return wasmLinspace(start, stop, num) as NumArray;
}

// ── Element-wise arithmetic ───────────────────────────────────────────────────

/**
 * Element-wise addition. Both operands must have the same shape,
 * or the second operand can be a scalar.
 */
function add(a: NumArray, b: NumArray | number): NumArray {
  if (typeof b === 'number') return a.add_scalar(b);
  return a.add_array(b);
}

/**
 * Element-wise subtraction.
 */
function sub(a: NumArray, b: NumArray | number): NumArray {
  if (typeof b === 'number') return a.sub_scalar(b);
  return a.sub_array(b);
}

/**
 * Element-wise multiplication.
 */
function mul(a: NumArray, b: NumArray | number): NumArray {
  if (typeof b === 'number') return a.mul_scalar(b);
  return a.mul_array(b);
}

/**
 * Element-wise division.
 */
function div(a: NumArray, b: NumArray | number): NumArray {
  if (typeof b === 'number') return a.div_scalar(b);
  return a.div_array(b);
}

// ── Reductions ────────────────────────────────────────────────────────────────

/** Sum of all elements. */
function sum(a: NumArray): number {
  return a.sum();
}

/** Minimum element. */
function min(a: NumArray): number {
  return a.min();
}

/** Maximum element. */
function max(a: NumArray): number {
  return a.max();
}

// ── Linear algebra ────────────────────────────────────────────────────────────

/**
 * 1-D dot product or 2-D matrix multiply.
 *
 * @example
 * const a = np.array([1,2,3,4], [2,2]);
 * const b = np.array([5,6,7,8], [2,2]);
 * const c = np.dot(a, b); // 2x2 matmul result
 */
function dot(a: NumArray, b: NumArray): NumArray {
  return a.dot(b);
}

// ── Manipulation ──────────────────────────────────────────────────────────────

/** Reshape an array to the given shape. */
function reshape(a: NumArray, shape: Shape): NumArray {
  return a.reshape(u32(shape));
}

/**
 * Return a contiguous flattened 1-D copy of the array.
 *
 * This is NumPy's free-function equivalent of `a.flatten()`.
 *
 * @example
 * const a = np.array([1,2,3,4], [2,2]);
 * np.ravel(a); // shape [4] → [1,2,3,4]
 */
function ravel(a: NumArray): NumArray {
  return a.flatten();
}

/**
 * Alias for `ravel` / `a.flatten()`. Not a NumPy free function, but kept
 * for ergonomic parity with the `.flatten()` method.
 */
function flatten(a: NumArray): NumArray {
  return a.flatten();
}

// ── Helper ────────────────────────────────────────────────────────────────────

/**
 * Convert a NumArray back to a nested JS array matching its shape.
 * For a scalar (shape=[]), returns a plain number.
 */
function toArray(a: NumArray): number | number[] | number[][] {
  const flat = Array.from(a.data());
  const shape = a.shape();

  if (shape.length === 0) return flat[0]; // scalar from dot product
  if (shape.length === 1) return flat;
  if (shape.length === 2) {
    const [rows, cols] = shape;
    const result: number[][] = [];
    for (let r = 0; r < rows; r++) {
      result.push(flat.slice(r * cols, r * cols + cols));
    }
    return result;
  }
  return flat; // >2-D: return flat for now
}

// ── Namespace export ──────────────────────────────────────────────────────────

export const np = {
  array,
  zeros,
  ones,
  arange,
  linspace,
  add,
  sub,
  mul,
  div,
  sum,
  min,
  max,
  dot,
  reshape,
  ravel,
  flatten,
  toArray,
};
