/**
 * Type shim for the wasm-bindgen generated module.
 * Actual types will be generated by `wasm-pack build` into packages/numjs/wasm/
 */
declare module '../wasm/numjs_core' {
  export class NdArray {
    constructor(data: Float64Array, shape: number[]): NdArray;
    shape(): number[];
    ndim(): number;
    size(): number;
    dtype(): string;
    data(): Float64Array;
    get(index: number): number;
    set(index: number, value: number): void;
    reshape(shape: number[]): NdArray;
    flatten(): NdArray;
    sum(): number;
    min(): number;
    max(): number;
    add_array(other: NdArray): NdArray;
    sub_array(other: NdArray): NdArray;
    mul_array(other: NdArray): NdArray;
    div_array(other: NdArray): NdArray;
    add_scalar(scalar: number): NdArray;
    sub_scalar(scalar: number): NdArray;
    mul_scalar(scalar: number): NdArray;
    div_scalar(scalar: number): NdArray;
    dot(other: NdArray): NdArray;
    free(): void;
  }

  export function zeros(shape: number[]): NdArray;
  export function ones(shape: number[]): NdArray;
  export function arange(start: number, stop: number, step: number): NdArray;
  export function linspace(start: number, stop: number, num: number): NdArray;
  export default function init(): Promise<void>;
}
